"""Amortised per-coordinate credit head.

The object
----------
DAM's tilted path measure induces a tilted posterior over finished graphs,
``p*(x1|xt) = p_base(x1|xt) * exp(-g(x1)) / Z``. Marginalising to one coordinate --
which is all DeFoG's rate ever reads (see :func:`defog.core.dam.marginal_rate`) --

    p*(x1^i = c | xt)  ~  p_base(x1^i = c | xt) * m_t(xt)[i, c]

    m_t(xt)[i, c] = E_base[ exp(-g(x1)) | x1^i = c, xt ]

``m`` has exactly the shape of the clean-graph head, so steering is an elementwise
product followed by renormalisation, and the rate follows through the audited
head->rate bridge. Because this modifies the HEAD and not the rate, the correction
transfers across ``eta`` and ``omega`` automatically -- unlike rate-space regression,
which is fitted against one ``eta`` and deployed at another
(``docs/dam_result.md``, the eta regime gap).

Why a regressor and not Monte Carlo
-----------------------------------
DAM estimates a value DIFFERENCE per state from K=8-12 continuations. Measured
split-half reliability of one such instruction: **0.144**. The same instruction at 384
continuations: **0.890** (``scripts/splithalf.py``). The signal is real, coordinate-
specific and strongly reproducible; the per-state estimator simply cannot see it. A
regressor does not pay per instruction -- every coordinate of every sample at every
state supervises one shared function.

Why generalised KL
------------------
``gkl(u, w) = u - w + w log(w/u)`` is the Bregman divergence generated by
``F = <x, log x>``, and **its minimiser in ``u`` is the conditional MEAN of ``w``** --
which is the definition of ``m``. That is the loss Discrete Guidance Matching
(arXiv:2509.21912) uses for the same purpose. Squared error also has the right
minimiser, but the target ``exp(-g)`` is positive and heavy-tailed and gKL handles it
far better.

Note ``m`` is ``E[exp(-g)]``, NOT ``exp(E[-g])``. Regressing the reward and
exponentiating afterwards is a different, Jensen-biased object -- the same trap the
``n_z`` averaging in :mod:`defog.core.dam` had to avoid.

Not the head that failed
------------------------
An earlier "scoring head" labelled a broken intermediate graph with the logP of the
ANCESTOR endpoint it was corrupted from. The same graph reached from two ancestors got
two labels, so the target was not a function of the input, and it was mixed with
own-logP labels on valid draws -- two conditional distributions in one dataset. Here the
input is ``(xt, t, i, c)``, the label is the reward of a genuine endpoint drawn from
``xt`` whose coordinate ``i`` equals ``c``, and the minimiser is a well-defined
conditional expectation. Label noise is what regression is for.
"""

from __future__ import annotations

import copy
import math
from typing import Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from .adapter import AdaLNAdapter

__all__ = [
    "CreditHead",
    "credit_gkl",
    "gather_log_m",
    "guided_logmarginals",
    "constant_baseline",
    "per_class_baseline",
    "edge_mask_of",
]


# ===========================================================================
# Loss and steering
# ===========================================================================
def credit_gkl(log_m: torch.Tensor, log_w: torch.Tensor) -> torch.Tensor:
    """``gkl(exp(log_m), exp(log_w))``, evaluated without an exp/log round trip.

    ``gkl(u, w) = u - w + w (log w - log u)``. Minimised in ``u`` at ``u = E[w]``, so
    regressing with this loss and a stochastic ``w`` recovers the conditional mean --
    which is exactly ``m``. Elementwise; the caller masks and reduces.
    """
    w = log_w.exp()
    return log_m.exp() - w + w * (log_w - log_m)


def gather_log_m(log_mX: torch.Tensor, log_mE: torch.Tensor,
                 X1: torch.Tensor, E1: torch.Tensor):
    """Pick the entry each sample actually supervises: the class the endpoint took.

    One ``(xt, x1)`` pair observes ONE class per coordinate. The other classes at that
    coordinate are supervised by other endpoints drawn from the same ``xt``; over the
    dataset every entry is covered. Standard conditional-expectation regression.
    """
    return (log_mX * X1).sum(-1), (log_mE * E1).sum(-1)


def guided_logmarginals(logp_X: torch.Tensor, logp_E: torch.Tensor,
                        log_mX: torch.Tensor, log_mE: torch.Tensor,
                        *, scale: float = 1.0):
    """Steer the head: ``p* ~ p_base * m``, renormalised. ``scale=1`` is exact.

    ``scale`` is a free knob AT INFERENCE -- no retraining -- because the credit head is
    fitted once and the guidance strength is applied at use time.
    """
    return (F.log_softmax(logp_X + scale * log_mX, dim=-1),
            F.log_softmax(logp_E + scale * log_mE, dim=-1))


def edge_mask_of(node_mask: torch.Tensor) -> torch.Tensor:
    """Real, upper-triangular edge slots -- each undirected edge counted once."""
    n = node_mask.shape[1]
    iu = torch.triu(torch.ones(n, n, device=node_mask.device, dtype=torch.bool), 1)
    return (node_mask[:, :, None] & node_mask[:, None, :]) & iu[None]


# ===========================================================================
# Gate-1 reference predictors
# ===========================================================================
def constant_baseline(log_w: torch.Tensor) -> float:
    """Best single number under gKL: the mean of ``w``. Returns ``log E[w]``."""
    return float(torch.logsumexp(log_w.reshape(-1), 0) - math.log(log_w.numel()))


def per_class_baseline(log_w: torch.Tensor, cls: torch.Tensor, n_cls: int,
                       mask: torch.Tensor) -> torch.Tensor:
    """Best ``one scalar per class`` under gKL: ``log E[w | class]``, shape ``(n_cls,)``.

    Gate 1 exists to beat this. If a per-class scalar matches the network, the credit is
    a per-element preference and no per-coordinate machinery is warranted -- the
    split-half `resid-2` result (0.802 vs raw 0.816) says it should not.
    """
    out = torch.full((n_cls,), float("-inf"), device=log_w.device)
    lw, cc = log_w[mask], cls[mask]
    for c in range(n_cls):
        sel = lw[cc == c]
        if sel.numel():
            out[c] = torch.logsumexp(sel, 0) - math.log(sel.numel())
    return out


# ===========================================================================
# The head
# ===========================================================================
class CreditHead(nn.Module):
    """Predicts ``log m_t(xt)[i, c]`` with the shape of the clean-graph head.

    The backbone is a TRAINABLE COPY of the base, so it inherits the graph
    understanding the base already has -- predicting "what will this become" and
    "what is this worth if coordinate i lands on c" need much the same features. The
    output layer is reinterpreted, not reshaped: the base's per-coordinate logits
    become ``log m``.

    Conditioning on the reward's target goes through an :class:`AdaLNAdapter`, the same
    mechanism the conditional adapters use, because ``m`` depends on the target through
    ``g``.

    Memory: a full copy of the base. On a 6GB card with a ~1.4GB base this fits, but
    ``backbone='shared'`` (frozen base + adapter only) is available if it does not.
    """

    def __init__(self, base, *, cond_dim: int = 1, cond_mean=None, cond_std=None,
                 log_clamp: float = 12.0, backbone: str = "copy",
                 n_node_classes: Optional[int] = None,
                 n_edge_classes: Optional[int] = None, **adapter_kw):
        super().__init__()
        if backbone not in ("copy", "shared"):
            raise ValueError("backbone must be 'copy' or 'shared'")
        self.backbone = backbone
        self.log_clamp = float(log_clamp)
        if backbone == "copy":
            self.net = copy.deepcopy(base)
            for p in self.net.parameters():
                p.requires_grad_(True)
        else:
            self.net = [base]                      # hidden from .parameters()
            for p in base.parameters():
                p.requires_grad_(False)
        self.adapter = AdaLNAdapter.for_base(
            base, cond_dim=cond_dim,
            cond_mean=cond_mean, cond_std=cond_std,
            name="credit_head", cond_type="credit", **adapter_kw)

        # ZERO-INIT GATED READOUT -- the same idiom AdaLNAdapter uses to start as an
        # exact no-op. The backbone's output layer carries a SKIP CONNECTION
        # (`transformer.py`: `X = mlp_out_X(X) + X_to_out`), so zeroing the MLP would
        # leave the input one-hot, not a constant. Instead the backbone's logits are
        # centred and gated to zero, and a learnable per-class bias carries the level.
        # At init `log m = bias` exactly, so the head IS the per-class baseline Gate 1
        # must beat -- any held-out improvement is unambiguous learning, and the
        # exp(arbitrary logit) blow-up that made the first smoke run hit |grad| = 4.8e5
        # cannot happen.
        dx = n_node_classes or base.limit_dist.num_node_classes
        de = n_edge_classes or base.limit_dist.num_edge_classes
        self.gate_X = nn.Parameter(torch.zeros(1))
        self.gate_E = nn.Parameter(torch.zeros(1))
        self.bias_X = nn.Parameter(torch.zeros(dx))
        self.bias_E = nn.Parameter(torch.zeros(de))

    @property
    def _net(self):
        return self.net if self.backbone == "copy" else self.net[0]

    def forward(self, X_t, E_t, t, node_mask, cond):
        net = self._net
        nd = {"X_t": X_t, "E_t": E_t,
              "y_t": torch.zeros(X_t.shape[0], 0, device=X_t.device),
              "t": t, "node_mask": node_mask}
        extra = net._compute_extra_data(nd)
        mod = self.adapter(cond, t)
        pred = net.forward(nd, extra, node_mask, cond_modulation=mod)
        # Centre before gating: only the SHAPE of the backbone's logits should enter,
        # the level is the bias's job. Without centring the gate would have to cancel an
        # arbitrary offset before it could express anything.
        lX = self.bias_X + self.gate_X * (pred.X - pred.X.mean(-1, keepdim=True))
        lE = self.bias_E + self.gate_E * (pred.E - pred.E.mean(-1, keepdim=True))
        c = self.log_clamp
        return lX.clamp(-c, c), lE.clamp(-c, c)

    @torch.no_grad()
    def init_bias(self, log_w_X, log_w_E=None):
        """Start at the best trivial predictor. Pass ``log E[w | class]`` per class (or
        a scalar ``log E[w]``); the head then reproduces that baseline exactly at
        iteration 0."""
        lx = torch.as_tensor(log_w_X, dtype=self.bias_X.dtype, device=self.bias_X.device)
        self.bias_X.copy_(lx.expand_as(self.bias_X).clone())
        # A per-class NODE bias has dx entries and cannot be reused for the de edge
        # classes -- they are different label spaces. Fall back to its mean, which is
        # the best scalar, unless an edge-specific vector is supplied.
        if log_w_E is None:
            le = lx.mean().expand_as(self.bias_E)
        else:
            le = torch.as_tensor(log_w_E, dtype=self.bias_E.dtype,
                                 device=self.bias_E.device).expand_as(self.bias_E)
        self.bias_E.copy_(le.clone())

    # --- persistence, matching the repo's adapter convention ----------------
    def save(self, path: str, **meta):
        torch.save({"state_dict": self.state_dict(), "backbone": self.backbone,
                    "log_clamp": self.log_clamp, "meta": meta}, path)

    @classmethod
    def load(cls, path: str, base, device="cpu", **kw):
        ck = torch.load(path, map_location=device, weights_only=False)
        h = cls(base, log_clamp=ck.get("log_clamp", 12.0),
                backbone=ck.get("backbone", "copy"), **kw)
        h.load_state_dict(ck["state_dict"])
        return h.to(device)
